version: '3'
services:
  nginx-proxy-manager:
    container_name: proxy-manager
    image: jlesage/nginx-proxy-manager
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - "/srv/nginx-proxymanager/config:/config:rw"
    environment:
        DISABLE_IPV6: 'true'

networks:
    default:
        external:
            name: proxy-network
